/* (T3) bd0114_commenting.baf */
IF
	Global("BD_POINT6","BD0114",4)  // Spider Cave: Rhinoceros Beetle appeared
	StateCheck("BDBEETRH",STATE_REALLY_DEAD)  // Rhinoceros Beetle
	Global("C#AjSoD_BD_BEETLE","BD0114",0)  
	!GlobalTimerNotExpired("BD_TIMER_RHINOTALK","BD0114")  
	IfValidForPartyDialog("Ajantis")  
THEN
	RESPONSE #100
		DisplayStringHead("Ajantis",@105)
		SetGlobal("C#AjSoD_BD_BEETLE","BD0114",1)  
END