/* bd4601_commenting_et.baf */
/* (T3) Comment in the Avernus Elevator */
IF
	GlobalGT("bd_plot","global",554)
	Global("C#AjSoD_bd_hellevator_ot","bd4601",0)  
	IfValidForPartyDialog("Ajantis")  
	!GlobalTimerNotExpired("bd_hellevator_timer","bd4601")  
	!ActuallyInCombat()
THEN
	RESPONSE #100
		SetGlobal("C#AjSoD_bd_hellevator_ot","bd4601",1)  // Avernus Elevator
		SetGlobalTimer("bd_hellevator_timer","bd4601",7)  
		DisplayStringHead("Ajantis",@116)
END