/* bdcut58_patch.baf
Ajantis was left standing in bd4700 - make sure he's coming to the last hell area, too */

IF
  Global("C#AjSoD_kicked_bd4700","global",1) //set in BDAJANTI.dlg, see below
  !Dead("Ajantis")
  !InParty("Ajantis")
THEN
  RESPONSE #100
    CutSceneId(Player1)
    MoveGlobal("bd4400","Ajantis",[1524.1281]) //coordinates somewhere near the portal in bd4400.are. 
    ActionOverride("Ajantis",Face(NW))     //or whatever so he is facing the portal
END